Bbcom 1049
mobitel-ltd/jira-to-matrix pull request #31
Opened 2017-10-02 15:56 UTC by disko23

2017-10-02 16:01 UTC, PragmaWolf requested changes

2017-10-02 16:01 UTC, PragmaWolf commented on src/matrix/timeline-handler.js
> +    sender = sender.substring(1, sender.length - 21);
Magic numbers
Что такое 21? Вынеси в константу с понятным названием

2017-10-02 16:06 UTC, disko23 commented on src/matrix/timeline-handler.js
> +    sender = sender.substring(1, sender.length - 21);
Исправил

2017-10-02 16:06 UTC, PragmaWolf approved these changes

2017-10-03 11:56 UTC, PragmaWolf requested changes

2017-10-03 11:56 UTC, PragmaWolf commented on src/matrix/timeline-handler.js
> +    const postfix = 21;
`postfix` можно вообще вынести в начало файла, чтобы он был выше области видимости конкретных функций, не придутся задавать его дважды.
А так я бы выкусывал нужное тебе несколько по другому, но пока норм.

2017-10-03 12:00 UTC, disko23 commented on src/matrix/timeline-handler.js
> +    const postfix = 21;
Поправил

2017-10-03 12:12 UTC, PragmaWolf approved these changes

2017-10-03 13:53 UTC, merged