Bbcom 1089
mobitel-ltd/jira-to-matrix pull request #36
Opened 2017-10-09 15:02 UTC by disko23

2017-10-09 23:58 UTC, PragmaWolf requested changes

2017-10-09 23:58 UTC, PragmaWolf commented on src/matrix/jira-commands.js
> +const {postfix} = require('../config').matrix;
`const {postfix, domain} = require('../config').matrix;`

2017-10-09 23:58 UTC, PragmaWolf commented on src/matrix/jira-commands.js
> +    const userId = `@${user}:matrix.bingo-boom.ru`;
`const userId = `@${user}:${domain}`;`

2017-10-10 07:55 UTC, disko23 commented on src/matrix/jira-commands.js
> +const {postfix} = require('../config').matrix;
Поправил

2017-10-10 07:55 UTC, disko23 commented on src/matrix/jira-commands.js
> +    const userId = `@${user}:matrix.bingo-boom.ru`;
Сделал

2017-10-10 08:23 UTC, PragmaWolf approved these changes

2017-10-10 08:25 UTC, merged