Bbcom 856
mobitel-ltd/jira-to-matrix pull request #42
Opened 2017-10-19 16:21 UTC by disko23

2017-10-19 19:23 UTC, PragmaWolf requested changes

2017-10-19 19:23 UTC, PragmaWolf commented on src/matrix/jira-commands.js
> +const chekUser = (users, name) => Boolean(
Тоже можно убрать Boolean. 
И в принципе бинарные операции менее читабельны чем обычное сравнение, тут на твое усмотрение

2017-10-19 19:23 UTC, PragmaWolf commented on src/matrix/jira-commands.js
> +const checkCommand = (body, name, index) => Boolean(
Тоже Booean и бинарники

2017-10-19 19:23 UTC, PragmaWolf commented on src/matrix/jira-commands.js
> +    return transitions.map(move => ({name: move.name, id: move.id}));
`return transitions.map({name, id} => ({name, id}));`

2017-10-19 19:23 UTC, PragmaWolf commented on src/matrix/jira-commands.js
> +    || String(index + 1) === name;
У меня такое ощущение что подобные проверки я у тебя уже встречал в прошлом пулл-реквесте, может, раз они одинаковые вынести их в отдельную функцию/модуль/утилиту, чтобы не дублировать код?

2017-10-20 08:40 UTC, disko23 commented on src/matrix/jira-commands.js
> +const chekUser = (users, name) => Boolean(
Поправил

2017-10-20 08:40 UTC, disko23 commented on src/matrix/jira-commands.js
> +const checkCommand = (body, name, index) => Boolean(
Поправил

2017-10-20 08:43 UTC, disko23 commented on src/matrix/jira-commands.js
> +    return transitions.map(move => ({name: move.name, id: move.id}));
Есть

2017-10-20 09:29 UTC, disko23 commented on src/matrix/jira-commands.js
> +    || String(index + 1) === name;
Перенес весь обработчик в отдельную папку
Создал модуль "чекер" в котором расположил все функции, возвращающие булево значение

2017-10-20 09:31 UTC, PragmaWolf approved these changes

2017-10-20 09:32 UTC, merged