Bbcom 1244
mobitel-ltd/jira-to-matrix pull request #50
Opened 2017-12-11 14:41 UTC by grigori-gru

2017-12-18 10:55 UTC, PragmaWolf requested changes
Боль-печаль

2017-12-18 10:55 UTC, PragmaWolf commented on src/app.js
> +tryRedis();
Зачем здесь повторный вызов? На 26 строке он уже есть. И было бы неплохо эти вызовы вообще выпилить

2017-12-18 10:55 UTC, PragmaWolf commented on src/app.js
> +        logger.error(`Uncaught exception!\n${err}`);
`${err} => [object Object]` не надо так

У тебя, ниже по коду, есть еще один обработчик события `uncaughtException`. Что помешало их совместить? Тем более, что после этого обработчика второй вообще никогда не запустится

2017-12-18 10:55 UTC, PragmaWolf commented on src/app.js
>  };
```javascript
const onExit = () => {
    clearInterval(tryRedis()); // здесь не удалится уже существующий интервал
    Matrix.disconnect();
    if (server.listening) {
        server.close();
    }

    process.exit(1);
};
```
и смотри комментарий выше, по поводу `tryRedis`

2017-12-18 10:55 UTC, PragmaWolf commented on src/app.js
> +    setInterval(() => queuePush.emit('startQueueHandler'), 30 * 60 * 1000);
Эта функция будет всегда возвращать ссылку на новый интервал. Правильней сделать так:
```javascript
const CHECK_QUEUE_DELAY = 30 * 60 * 1000;
let checkQueueInterval = setInterval(() => {
    queuePush.emit('startQueueHandler')
}, CHECK_QUEUE_DELAY);
checkQueueInterval.unref();
```
И в дальнейшем пользоваться для работы с этим интервалом переменной `checkQueueInterval`.
И при таком подходе не потребуется потом дергать функцию, которую ты, почему-то, назвал `tryRedis`

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/create-room.js
>      const participants = (await jira.issue.collectParticipants(issue)).map(
А если `await jira.issue.collectParticipants(issue)` вернет `undefined`? а если `null`? Полетит бот по эксепшенам на вылет? Хотя бы `try-catch` добавь...

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/helper.js
> +    const values = ['name', 'key', 'summary'].map(key => issue[key]);
Простой тест:
```javascript
const issue = {
    key: 'lalala',
};
const values = ['name', 'key', 'summary'].map(key => issue[key]);
console.log(values); // ==>> [ undefined, 'lalala', undefined ]
```
Ты уверен что у тебя в коде всё правильно?
`map` возвращает массив, а ты с ним потом как с объектом работаешь

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/invite-new-members.js
> +            .map(helpers.userID);
Я бы в таких случаях предпочитал бы проверку того, что вернулось из `await jira.issue.collectParticipants(issue)` и отправку в `throw` более конкретной ошибки, чем сообщение что нет метода `map` у `undefined`

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/invite-new-members.js
> +            logger.info(`New members invited to ${issue.key}: ${newMembers}`);
`${newMembers} // ==>> [object Object]`

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-comment.js
> +module.exports = {postComment};
Если ты возвращаешь только одну функцию, можно в принципе писать 
```javascript
module.exports = async ({mclient, issueID, headerText, comment, author}) => {...
```

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-epic-updates.js
>      const [err, saved] = await to(
выпили уже этот модуль `await-to-js`

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-epic-updates.js
>          redis.sismemberAsync(epicRedisKey(epicID), issueID)
```javascript
const redisKey = epicRedisKey(epicID);
await redis.sismemberAsync(redisKey, issueID);
```

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-epic-updates.js
>          redis.saddAsync(epicRedisKey(epicID), issueID)
Модуль `await-to-js` и функция как параметр

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-issue-description.js
> +        await jira.issue.renderedValues(issue.id, ['description'])
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию. Тем более `async`. Тем более без `try-catch`

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-issue-description.js
> +        getTutorial()
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию.

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-issue-description.js
> +        lodash.get(issue.fields, address) || translate('miss')
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию.

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-epic-updates.js
>          marked(translate('issueAddedToEpic', values))
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию.

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-issue-updates.js
>      const messageHeader = () => `${author} ${translate('issue_updated', null, author)}`;
Зачем тут функция? Она не принимает никаких параметров, а берет их из родительской области видимости.
Последующий её вызов `messageHeader(author)` по сути не имеет смысла, так как параметр переданный в функцию в ней не используется

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-issue-updates.js
> +            await jira.issue.renderedValues(key, fields)
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию. Тем более `async`. Тем более без `try-catch`

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-issue-updates.js
>          .concat(changesDescription(fields, formattedValues))
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию.

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-issue-updates.js
> +                formattedValues,
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию.

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-new-links.js
> +        if (!links || links.length === 0) {
А здесь не нужно усилить проверку `if (!links || links.length === 0 || typeof status !== 'string') {`?

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-project-updates.js
>          marked(translate('statusEpicChangedMessage', values, values['user.name']))
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию.

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/post-project-updates.js
>          marked(translate('epicAddedToProject', values, values['user.name']))
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию.

2017-12-18 10:55 UTC, PragmaWolf commented on src/bot/save-incoming.js
> +module.exports = {newSave};
Можно сразу возвращать `module.exports = async data => {`

2017-12-18 10:55 UTC, PragmaWolf commented on src/config/validate-config.js
> +    },
Эта запись настроек лога должна быть в конфиге, а не в схеме, которая конфиг проверяет. Здесь должна быть схема, которая проверят правильность настроек лога в конфиге.

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/epic.js
>  module.exports = {issuesIn};
Можно возвращать как `module.exports = async epicKey => {`

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/issue.js
>          if (body && body.watchers instanceof Array) {
`body.watchers instanceof Array` лучше записать как `Array.isArray(body.watchers)`

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/common.js
> +/* :{}*/
JSDoc пишутся не так - http://usejsdoc.org/

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/link.js
>  module.exports = {get};
Можно возвращать `module.exports = async id => {`

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/issue.js
> +/* :string*/
JSDoc пишутся не так - http://usejsdoc.org/

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/issue.js
> +/* :string*/
JSDoc пишутся не так - http://usejsdoc.org/

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/issue.js
> +/* :?string*/
JSDoc пишутся не так - http://usejsdoc.org/

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/common.js
> +/* :string*/
JSDoc пишутся не так - http://usejsdoc.org/

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/issue.js
> +/* :{}*/
JSDoc пишутся не так - http://usejsdoc.org/

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/issue.js
> +/* :Array<{}>*/
JSDoc пишутся не так - http://usejsdoc.org/

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/issue.js
> +/* :string*/
JSDoc пишутся не так - http://usejsdoc.org/

2017-12-18 10:55 UTC, PragmaWolf commented on src/jira/issue.js
> +/* :string[]*/
JSDoc пишутся не так - http://usejsdoc.org/

2017-12-18 10:55 UTC, PragmaWolf commented on src/matrix/api-client.js
>          return;
Удали неиспользуемый, закомментированный код в файле

2017-12-18 10:55 UTC, PragmaWolf commented on src/matrix/api-client.js
> +        const {room_id} = await client.getRoomIdForAlias(getAlias(alias));
Можно использовать переименование при деструктуризации `{room_id: roomId}`

2017-12-18 10:55 UTC, PragmaWolf commented on src/matrix/api-client.js
> +        const roomID = await client.getRoomIdForAlias(getAlias(alias));
Можно деструктуризовать`{room_id: roomId}`

2017-12-18 10:55 UTC, PragmaWolf commented on src/matrix/api-client.js
> +            getAlias(alias),
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию.

2017-12-18 10:55 UTC, PragmaWolf commented on src/matrix/index.js
> +            return new Promise(this._executor.bind(this));
Здесь разве нужно вот так явно возвращать промис? Это же `async`-функция

2017-12-18 10:55 UTC, PragmaWolf commented on src/matrix/index.js
> +        return result;
`try ... catch`?

2017-12-18 10:55 UTC, PragmaWolf commented on src/matrix/timeline-handler/commands/helper.js
> +    const START_ACC = [];
Эти константы лучше вообще вынести за пределы функции в область видимости модуля

2017-12-18 10:55 UTC, PragmaWolf commented on src/matrix/timeline-handler/commands/helper.js
> +const BASE_URL = `${url}/rest/api/2/issue`;
Подними константу в начало файла, пожалуйста

2017-12-18 10:55 UTC, PragmaWolf commented on src/matrix/timeline-handler/index.js
>  const translate = require('../../locales');
Удаляем ненужный закомментированный код

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/bot-handler.js
> +);
Возможно стоит заменить `should` на `is`

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/bot-handler.js
> +        postLinkedChanges: shouldPostLinkedChanges(body),
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию.

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/get-parsed-and-save-to-redis.js
> +
Лишняя строка

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/bot-handler.js
> +
Лишняя строка

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/index.js
> +            .filter(key => key.indexOf('|') === -1);
Получи отдельно данные из Redis и отдельно их отфильтруй

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/index.js
> +        dataFromRedis.forEach(value => logger.debug('dataFromRedis', value));
Дополнительный цикл только для логирования данных? Серьезно?!

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/index.js
> +                    await createRoom({...createRoomData, mclient: await client});
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию. Тем более `async`.

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/index.js
> +                await bot[funcName]({...data, mclient: await client});
Не надо передавать напрямую результат работы функции в качестве параметра в другую функцию. Тем более `async`.

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/index.js
> +        botFuncHandlingResult.forEach(value => logger.info('result of Promise.all in queue', value));
Дополнительный цикл только для логирования данных? Серьезно?!

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/parse-body.js
> +    const headerText = getheaderText(body);
`getHeaderText`

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/parse-body.js
> +const getheaderText = ({comment, webhookEvent}) => {
`getHeaderText`

2017-12-18 10:55 UTC, PragmaWolf commented on src/queue/parse-body.js
> +        name: body.user.name,
Выше ты используешь `Ramda` для получения параметров из `body`, а тут нет. Тут ты почему-то 100% уверен в существовании `body.user.name`?

2017-12-18 10:55 UTC, PragmaWolf commented on src/redis-client.js
>          process.exit(1);
В `logger.error(`Error while creating redis client ${error}`);` `${error} //=> [object Object]`

2017-12-24 19:02 UTC, PragmaWolf approved these changes

2017-12-24 19:57 UTC, PragmaWolf approved these changes
A few more fixies

2017-12-24 19:57 UTC, PragmaWolf commented on src/bot/post-project-updates.js
>          marked(translate('statusEpicChangedMessage', values, values['user.name']))
А почему это проигнорировал?

2017-12-24 19:57 UTC, PragmaWolf commented on newReadme.md
> +* use command from Matrix Riot to integrate with Jira and make different actions.
Это README таки на английском или на русском?

2017-12-24 19:57 UTC, PragmaWolf commented on src/app.js
> +checkQueueInterval.unref();
Перемести на 31 строчку, пожалуйста

2017-12-24 19:57 UTC, PragmaWolf commented on src/bot/index.js
>  const postLinkedChanges = require('./post-linked-changes');
Почему нет расширений у файлов?

2017-12-24 19:57 UTC, PragmaWolf commented on src/config/index.js
А почему это проигнорировал?

2017-12-24 19:57 UTC, PragmaWolf commented on src/matrix/api-client.js
> +        const roomID = await client.getRoomIdForAlias(getAlias(alias));
А почему это проигнорировал?

2017-12-24 19:57 UTC, PragmaWolf commented on src/matrix/api-client.js
>          return;
А почему это проигнорировал?

2017-12-24 19:57 UTC, PragmaWolf commented on src/matrix/index.js
> +            return new Promise(this._executor.bind(this));
А почему это проигнорировал?

2017-12-24 19:57 UTC, PragmaWolf commented on src/redis-client.js
>          process.exit(1);
А почему это проигнорировал?

2017-12-24 19:57 UTC, PragmaWolf commented on src/utils/rest.js
> +        logger.error(`Error in fetchJSON ${url}:\n ${err}`);
В `logger.error(`Error in fetchJSON ${url}:\n ${err}`);` `${err} //=> [object Object]`

2017-12-24 19:57 UTC, PragmaWolf commented on src/utils/rest.js
> +        logger.error(`Error while getting ${url}:\n ${err}`);
В `logger.error(`Error while getting ${url}:\n ${err}`);` `${err} //=> [object Object]`

2017-12-24 19:57 UTC, PragmaWolf commented on src/utils/rest.js
> +        logger.error(`Error while getting ${url}:\n${err}`);
В `logger.error(`Error while getting ${url}:\n${err}`);` `${err} //=> [object Object]`

2017-12-24 20:00 UTC, PragmaWolf requested changes
A few more fixies (Mistakenly closed the previous review)

2017-12-25 10:08 UTC, grigori-gru commented on src/matrix/index.js
> +            return new Promise(this._executor.bind(this));
Я не нашел лучше выхода, чтобы отложить последующие действия до синхронизации матрикса.

2017-12-25 10:11 UTC, grigori-gru commented on src/redis-client.js
>          process.exit(1);
client.on('error', err => {
    logger.error(`Redis error:\n${err}`);
    if (/\bECONNREFUSED\b/.test(err.message || '')) {
        process.exit(1);
    }
});
Этот кусок вообще непонятно зачем нужен

2017-12-25 10:15 UTC, grigori-gru commented on src/app.js
> +checkQueueInterval.unref();
```
const checkQueueInterval = setInterval(() => {
    queuePush.emit('startQueueHandler');
}, CHECK_QUEUE_DELAY);
const client = connectToMatrix();
checkQueueInterval.unref();
```

2017-12-25 10:16 UTC, grigori-gru commented on src/app.js
> +checkQueueInterval.unref();
Так?

2017-12-26 13:53 UTC, PragmaWolf requested changes

2017-12-26 13:53 UTC, PragmaWolf commented on src/app.js
> +checkQueueInterval.unref();
Так
```javascript
const checkQueueInterval = setInterval(() => {
    queuePush.emit('startQueueHandler');
}, CHECK_QUEUE_DELAY);
checkQueueInterval.unref();

const client = connectToMatrix();
```
Чтобы потом не искать по всему файлу сделал ты `unref` для таймера или нет

2017-12-26 13:53 UTC, PragmaWolf commented on src/redis-client.js
>          process.exit(1);
где ты его взял? я писал про логгер в
```javascript
try {
     result = redis.createClient(config);
} catch (error) {
     logger.error(`Error while creating redis client ${error}`);
     process.exit(1);
}
```

2017-12-26 13:59 UTC, PragmaWolf requested changes

2017-12-26 13:59 UTC, PragmaWolf commented on newReadme.md
> +* use command from Matrix Riot to integrate with Jira and make different actions.
up

2017-12-26 13:59 UTC, PragmaWolf commented on src/bot/index.js
>  const postLinkedChanges = require('./post-linked-changes');
up

2017-12-26 13:59 UTC, PragmaWolf commented on src/bot/post-project-updates.js
>          marked(translate('statusEpicChangedMessage', values, values['user.name']))
up

2017-12-26 13:59 UTC, PragmaWolf commented on src/config/index.js
up

2017-12-26 13:59 UTC, PragmaWolf commented on src/matrix/api-client.js
> +        const roomID = await client.getRoomIdForAlias(getAlias(alias));
up

2017-12-26 13:59 UTC, PragmaWolf commented on src/matrix/api-client.js
>          return;
up

2017-12-26 13:59 UTC, PragmaWolf commented on src/utils/rest.js
> +        logger.error(`Error in fetchJSON ${url}:\n ${err}`);
up

2017-12-26 13:59 UTC, PragmaWolf commented on src/utils/rest.js
> +        logger.error(`Error while getting ${url}:\n ${err}`);
up

2017-12-26 13:59 UTC, PragmaWolf commented on src/utils/rest.js
> +        logger.error(`Error while getting ${url}:\n${err}`);
up

2017-12-26 14:23 UTC, grigori-gru commented on src/bot/post-project-updates.js
>          marked(translate('statusEpicChangedMessage', values, values['user.name']))
Так вроде, исправлено уже

2017-12-26 15:29 UTC, PragmaWolf approved these changes

2017-12-26 15:34 UTC, merged