new create data
mobitel-ltd/jira-to-matrix pull request #57
Opened 2018-01-12 15:12 UTC by grigori-gru

2018-01-13 14:42 UTC, PragmaWolf requested changes

2018-01-13 14:42 UTC, PragmaWolf commented on src/queue/redis-data-handle.js
> +        const redisKeys = allKeys.filter(key => key.indexOf('|') === -1 && key.indexOf('rooms') === -1);
`key.indexOf('|') === -1 && key.indexOf('rooms') === -1`
можно чуть более упростить:
`key.includes('|') && key.includes('rooms')`

2018-01-13 14:42 UTC, PragmaWolf commented on src/queue/redis-data-handle.js
> +        const result = await Promise.all(allKeys.map(async key => {
В случае ошибки метод свалится в `catch`. Может быть лучше сделать так, чтобы метод в любом случае возвращал массив, просто заполненный валидными данными и `false` в случае неудачи? Его потом можно будет просто отфильтровать - как у тебя сделано в функции `handleRedisRooms` расположенной ниже

2018-01-13 14:42 UTC, PragmaWolf commented on src/queue/redis-data-handle.js
> +        const handledRooms = await Promise.all(roomsData.map(async data => {
В принципе метод который ты создаешь для обработки `roomsData.map` можно вынести в отдельную функцию

2018-01-13 14:42 UTC, PragmaWolf commented on src/queue/redis-data-handle.js
> +        const result = await Promise.all(dataFromRedis.map(async ({redisKey, funcName, data}) => {
В принципе метод который ты создаешь для обработки `dataFromRedis.map` можно вынести в отдельную функцию

2018-01-15 07:54 UTC, grigori-gru commented on src/queue/redis-data-handle.js
> +        const handledRooms = await Promise.all(roomsData.map(async data => {
У меня внутри него `client` из окружения `handleRedisRooms`. Могу так только:
```
const handleRedisRooms = async (client, roomsData = []) => {
    const roomHandle = async data => {
        try {
....................
    };
    try {
        const handledRooms = await Promise.all(roomsData.map(roomHandle));
.....................
        }
    } catch (err) {
        logger.error('handleRedisRooms error', err);
    }
};

```

2018-01-15 07:59 UTC, PragmaWolf commented on src/queue/redis-data-handle.js
> +        const handledRooms = await Promise.all(roomsData.map(async data => {
Оставь тогда как есть
Вот из-за такого протаскивания важного объекта из метода в метод я и не очень люблю такой подход.

2018-01-15 09:53 UTC, PragmaWolf approved these changes

2018-01-15 09:53 UTC, merged